# Generated by Django 4.2.4 on 2023-10-02 00:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0004_follow_delete_followers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="comments",
            field=models.ManyToManyField(
                blank=True,
                related_name="commented_posts",
                to="network.comment",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_posts", to="network.like"
            ),
        ),
    ]
